org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

loader_version=0.19.3
loom_version=1.17-SNAPSHOT
mpp_version=2.0.0

mod_version=1.0.0
mod_name=More Mining Stages
mod_id=moreminingstages
mod_description=

update_name_suffix= - Initial Release
maven_group=com.axialeaa

target_version=~26.2
build_version=26.2
modrinth_versions=26.2
fabric_api_version=0.154.0+26.2
modmenu_version=20.0.0-beta.4
mixinsquared_version=0.3.7-beta.3

modrinth_project_id=1a2b3c4d
repository_url=axialeaa/ExampleMod